CREATE TABLE IF NOT EXISTS reward_records (
  id BIGSERIAL PRIMARY KEY,
  dataset_id BIGINT NOT NULL REFERENCES datasets(id) ON DELETE CASCADE,
  question_id BIGINT NOT NULL UNIQUE REFERENCES questions(id) ON DELETE CASCADE,
  score DOUBLE PRECISION NOT NULL,
  object_key TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'generated',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
